config/routes.rb
RedmineApp::Application.routes.draw do
  match 'query_per_project/redirect_to_user_query', :to => 'query_per_project#redirect_to_user_query', :via => [:get, :post]
end

app/controllers/query_per_project_controller.rb
require 'query_per_project_constants'

class QueryPerProjectController < ApplicationController
  unloadable

  #before_filter :require_login
  before_action :require_login

  def redirect_to_user_query
    q = Query.first(:conditions => ["name = ? AND user_id = ?", QPP_Constants::settings['my_home_query_name'],User.current.id])
    q = Query.find_by_name(QPP_Constants::MY_QUERY_HOME_NAME_DEFAULT) unless q
    if q
      redirect_to :controller => 'issues', :project_id => q.project, :query_id => q
    else
      redirect_to :controller => 'my', :action => 'page'
    end
  end

end

app/views/queries/_query_form.html.erb
<%= hidden_field_tag 'set_filter', '1' %>
<%= hidden_field_tag 'type', @query.type, :disabled => true, :id => 'query_type' %>
<%= query_hidden_sort_tag(@query) %>

<div id="query_form_with_buttons" class="hide-when-print">
<div id="query_form_content">
<%# VVK changes start %>
    <fieldset id="filters" class="collapsible <%= @query.new_record? && @query.name != "_QPP_"  ? "" : "collapsed" %>">
<%# VVK changes end %>
    <legend onclick="toggleFieldset(this);"><%= l(:label_filter_plural) %></legend>
<%# VVK changes start %>
      <div style="<%= @query.new_record? && @query.name != "_QPP_" ? "" : "display: none;" %>">
<%# VVK changes end %>
      <%= render :partial => 'queries/filters', :locals => {:query => @query} %>
    </div>
  </fieldset>

  <fieldset id="options" class="collapsible collapsed">
    <legend onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
    <div style="display: none;">
      <table>
        <tr>
          <td class="field"><%= l(:field_column_names) %></td>
          <td><%= render_query_columns_selection(@query) %></td>
        </tr>
        <% if @query.groupable_columns.any? %>
        <tr>
          <td class="field"><label for='group_by'><%= l(:field_group_by) %></label></td>
          <td><%= group_by_column_select_tag(@query) %></td>
        </tr>
        <% end %>
        <% if @query.available_block_columns.any? %>
        <tr>
          <td class="field"><%= l(:button_show) %></td>
          <td><%= available_block_columns_tags(@query) %></td>
        </tr>
        <% end %>
        <% if @query.available_totalable_columns.any? %>
        <tr>
          <td><%= l(:label_total_plural) %></td>
          <td><%= available_totalable_columns_tags(@query) %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </fieldset>
</div>

<p class="buttons">
  <%= link_to_function l(:button_apply), '$("#query_form").submit()', :class => 'icon icon-checked' %>
  <%= link_to l(:button_clear), { :set_filter => 1, :sort => '', :project_id => @project }, :class => 'icon icon-reload'  %>
  <% if @query.new_record? %>
    <% if User.current.allowed_to?(:save_queries, @project, :global => true) %>
      <%= link_to_function l(:button_save),
                           "$('#query_type').prop('disabled',false);$('#query_form').attr('action', '#{ @project ? new_project_query_path(@project) : new_query_path }').submit()",
                           :class => 'icon icon-save' %>
    <% end %>
  <% else %>
    <% if @query.editable_by?(User.current) %>
      <%= link_to l(:button_edit), edit_query_path(@query), :class => 'icon icon-edit' %>
      <%= delete_link query_path(@query) %>
    <% end %>
  <% end %>
</p>
</div>

<%= error_messages_for @query %>

app/views/settings/_default_columns_settings.html.erb
<p>
  <%= label_tag('settings[query_templates_project_id]', l(:label_plugin_dc_query_project)) %>
  <%= select_tag( 'settings[query_templates_project_id]',
      dc_fill_projects_dropdown(@settings['query_templates_project_id']))%>
</p>

<p>
  <%= label_tag('settings[type_custom_field_name]', l(:label_plugin_dc_custom_field_name)) %>
  <%= select_tag( 'settings[type_custom_field_name]',
      dc_fill_custom_fields_dropdown(@settings['type_custom_field_name']))%>
</p>

<p>
  <%= label_tag('settings[my_global_query_name]', l(:label_plugin_dc_my_global_name)) %>
  <%= text_field_tag 'settings[my_global_query_name]', @settings['my_global_query_name'], {:size => 30, :maxlength => 30 } %>
</p>

<p>
  <%= label_tag('settings[my_default_query_name]', l(:label_plugin_dc_my_default_name)) %>
  <%= text_field_tag 'settings[my_default_query_name]', @settings['my_default_query_name'], {:size => 30, :maxlength => 30 } %>
</p>

<p>
  <%= label_tag('settings[default_query_name]', l(:label_plugin_dc_default_name)) %>
  <%= text_field_tag 'settings[default_query_name]', @settings['default_query_name'], {:size => 30, :maxlength => 30 } %>
</p>

<p>
  <%= label_tag('settings[my_home_query_name]', l(:label_plugin_dc_my_home_default_name)) %>
  <%= text_field_tag 'settings[my_home_query_name]', @settings['my_home_query_name'], {:size => 30, :maxlength => 30 } %>
</p>